name: Daily Release Check

on:
  workflow_dispatch:
  schedule:
    - cron: "34 6 * * *"

jobs:
  release-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install pygithub quicklogs docker click

      - name: Run release check script
        run: python ci.py release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
